import { GL_STATIC_VARIABLES } from './static-variables';

export enum GL_TEXTURES {
  NEAREST = GL_STATIC_VARIABLES.NEAREST,
  LINEAR = GL_STATIC_VARIABLES.LINEAR,
  NEAREST_MIPMAP_NEAREST = GL_STATIC_VARIABLES.NEAREST_MIPMAP_NEAREST,
  LINEAR_MIPMAP_NEAREST = GL_STATIC_VARIABLES.LINEAR_MIPMAP_NEAREST,
  NEAREST_MIPMAP_LINEAR = GL_STATIC_VARIABLES.NEAREST_MIPMAP_LINEAR,
  LINEAR_MIPMAP_LINEAR = GL_STATIC_VARIABLES.LINEAR_MIPMAP_LINEAR,

  /**
   * Texture magnification filter
   *
   * @param
   * * `gl.LINEAR` (default value)
   * * `gl.NEAREST`
   */
  TEXTURE_MAG_FILTER = GL_STATIC_VARIABLES.TEXTURE_MAG_FILTER,

  /**
   * Texture minification filter
   *
   * @param
   * * `gl.LINEAR`
   * * `gl.NEAREST`
   * * `gl.NEAREST_MIPMAP_NEAREST`
   * * `gl.LINEAR_MIPMAP_NEAREST`
   * * `gl.NEAREST_MIPMAP_LINEAR` (default value)
   * * `gl.LINEAR_MIPMAP_LINEAR`
   */
  TEXTURE_MIN_FILTER = GL_STATIC_VARIABLES.TEXTURE_MIN_FILTER,

  /**
   * Wrapping function for texture coordinate `s`
   *
   * @param
   * * `gl.REPEAT` (default value)
   * * `gl.CLAMP_TO_EDGE`
   * * `gl.MIRRORED_REPEAT`
   */
  TEXTURE_WRAP_S = GL_STATIC_VARIABLES.TEXTURE_WRAP_S,

  /**
   * Wrapping function for texture coordinate `t`
   *
   * @param
   * * `gl.REPEAT` (default value)
   * * `gl.CLAMP_TO_EDGE`
   * * `gl.MIRRORED_REPEAT`
   */
  TEXTURE_WRAP_T = GL_STATIC_VARIABLES.TEXTURE_WRAP_T,
  TEXTURE_2D = GL_STATIC_VARIABLES.TEXTURE_2D,
  TEXTURE = GL_STATIC_VARIABLES.TEXTURE,
  TEXTURE_CUBE_MAP = GL_STATIC_VARIABLES.TEXTURE_CUBE_MAP,
  TEXTURE_BINDING_CUBE_MAP = GL_STATIC_VARIABLES.TEXTURE_BINDING_CUBE_MAP,
  TEXTURE_CUBE_MAP_POSITIVE_X = GL_STATIC_VARIABLES.TEXTURE_CUBE_MAP_POSITIVE_X,
  TEXTURE_CUBE_MAP_NEGATIVE_X = GL_STATIC_VARIABLES.TEXTURE_CUBE_MAP_NEGATIVE_X,
  TEXTURE_CUBE_MAP_POSITIVE_Y = GL_STATIC_VARIABLES.TEXTURE_CUBE_MAP_POSITIVE_Y,
  TEXTURE_CUBE_MAP_NEGATIVE_Y = GL_STATIC_VARIABLES.TEXTURE_CUBE_MAP_NEGATIVE_Y,
  TEXTURE_CUBE_MAP_POSITIVE_Z = GL_STATIC_VARIABLES.TEXTURE_CUBE_MAP_POSITIVE_Z,
  TEXTURE_CUBE_MAP_NEGATIVE_Z = GL_STATIC_VARIABLES.TEXTURE_CUBE_MAP_NEGATIVE_Z,
  MAX_CUBE_MAP_TEXTURE_SIZE = GL_STATIC_VARIABLES.MAX_CUBE_MAP_TEXTURE_SIZE,
  TEXTURE0 = GL_STATIC_VARIABLES.TEXTURE0,
  TEXTURE1 = GL_STATIC_VARIABLES.TEXTURE1,
  TEXTURE2 = GL_STATIC_VARIABLES.TEXTURE2,
  TEXTURE3 = GL_STATIC_VARIABLES.TEXTURE3,
  TEXTURE4 = GL_STATIC_VARIABLES.TEXTURE4,
  TEXTURE5 = GL_STATIC_VARIABLES.TEXTURE5,
  TEXTURE6 = GL_STATIC_VARIABLES.TEXTURE6,
  TEXTURE7 = GL_STATIC_VARIABLES.TEXTURE7,
  TEXTURE8 = GL_STATIC_VARIABLES.TEXTURE8,
  TEXTURE9 = GL_STATIC_VARIABLES.TEXTURE9,
  TEXTURE10 = GL_STATIC_VARIABLES.TEXTURE10,
  TEXTURE11 = GL_STATIC_VARIABLES.TEXTURE11,
  TEXTURE12 = GL_STATIC_VARIABLES.TEXTURE12,
  TEXTURE13 = GL_STATIC_VARIABLES.TEXTURE13,
  TEXTURE14 = GL_STATIC_VARIABLES.TEXTURE14,
  TEXTURE15 = GL_STATIC_VARIABLES.TEXTURE15,
  TEXTURE16 = GL_STATIC_VARIABLES.TEXTURE16,
  TEXTURE17 = GL_STATIC_VARIABLES.TEXTURE17,
  TEXTURE18 = GL_STATIC_VARIABLES.TEXTURE18,
  TEXTURE19 = GL_STATIC_VARIABLES.TEXTURE19,
  TEXTURE20 = GL_STATIC_VARIABLES.TEXTURE20,
  TEXTURE21 = GL_STATIC_VARIABLES.TEXTURE21,
  TEXTURE22 = GL_STATIC_VARIABLES.TEXTURE22,
  TEXTURE23 = GL_STATIC_VARIABLES.TEXTURE23,
  TEXTURE24 = GL_STATIC_VARIABLES.TEXTURE24,
  TEXTURE25 = GL_STATIC_VARIABLES.TEXTURE25,
  TEXTURE26 = GL_STATIC_VARIABLES.TEXTURE26,
  TEXTURE27 = GL_STATIC_VARIABLES.TEXTURE27,
  TEXTURE28 = GL_STATIC_VARIABLES.TEXTURE28,
  TEXTURE29 = GL_STATIC_VARIABLES.TEXTURE29,
  TEXTURE30 = GL_STATIC_VARIABLES.TEXTURE30,
  TEXTURE31 = GL_STATIC_VARIABLES.TEXTURE31,
  ACTIVE_TEXTURE = GL_STATIC_VARIABLES.ACTIVE_TEXTURE,
  REPEAT = GL_STATIC_VARIABLES.REPEAT,
  CLAMP_TO_EDGE = GL_STATIC_VARIABLES.CLAMP_TO_EDGE,
  MIRRORED_REPEAT = GL_STATIC_VARIABLES.MIRRORED_REPEAT,

  // --- Additional constants defined WebGL 2
  RED = GL_STATIC_VARIABLES.RED,
  RGB8 = GL_STATIC_VARIABLES.RGB8,
  RGBA8 = GL_STATIC_VARIABLES.RGBA8,
  RGB10_A2 = GL_STATIC_VARIABLES.RGB10_A2,
  TEXTURE_3D = GL_STATIC_VARIABLES.TEXTURE_3D,

  /** Wrapping function for texture coordinate `r` */
  TEXTURE_WRAP_R = GL_STATIC_VARIABLES.TEXTURE_WRAP_R,

  /** Texture minimum level-of-detail value */
  TEXTURE_MIN_LOD = GL_STATIC_VARIABLES.TEXTURE_MIN_LOD,

  /** Texture maximum level-of-detail value */
  TEXTURE_MAX_LOD = GL_STATIC_VARIABLES.TEXTURE_MAX_LOD,

  /** Texture mipmap level */
  TEXTURE_BASE_LEVEL = GL_STATIC_VARIABLES.TEXTURE_BASE_LEVEL,

  /** Maximum texture mipmap array level */
  TEXTURE_MAX_LEVEL = GL_STATIC_VARIABLES.TEXTURE_MAX_LEVEL,

  /** Texture comparison mode */
  TEXTURE_COMPARE_MODE = GL_STATIC_VARIABLES.TEXTURE_COMPARE_MODE,

  /** Texture Comparison function */
  TEXTURE_COMPARE_FUNC = GL_STATIC_VARIABLES.TEXTURE_COMPARE_FUNC,
  SRGB = GL_STATIC_VARIABLES.SRGB,
  SRGB8 = GL_STATIC_VARIABLES.SRGB8,
  SRGB8_ALPHA8 = GL_STATIC_VARIABLES.SRGB8_ALPHA8,
  COMPARE_REF_TO_TEXTURE = GL_STATIC_VARIABLES.COMPARE_REF_TO_TEXTURE,
  RGBA32F = GL_STATIC_VARIABLES.RGBA32F,
  RGB32F = GL_STATIC_VARIABLES.RGB32F,
  RGBA16F = GL_STATIC_VARIABLES.RGBA16F,
  RGB16F = GL_STATIC_VARIABLES.RGB16F,
  TEXTURE_2D_ARRAY = GL_STATIC_VARIABLES.TEXTURE_2D_ARRAY,
  TEXTURE_BINDING_2D_ARRAY = GL_STATIC_VARIABLES.TEXTURE_BINDING_2D_ARRAY,
  R11F_G11F_B10F = GL_STATIC_VARIABLES.R11F_G11F_B10F,
  RGB9_E5 = GL_STATIC_VARIABLES.RGB9_E5,
  RGBA32UI = GL_STATIC_VARIABLES.RGBA32UI,
  RGB32UI = GL_STATIC_VARIABLES.RGB32UI,
  RGBA16UI = GL_STATIC_VARIABLES.RGBA16UI,
  RGB16UI = GL_STATIC_VARIABLES.RGB16UI,
  RGBA8UI = GL_STATIC_VARIABLES.RGBA8UI,
  RGB8UI = GL_STATIC_VARIABLES.RGB8UI,
  RGBA32I = GL_STATIC_VARIABLES.RGBA32I,
  RGB32I = GL_STATIC_VARIABLES.RGB32I,
  RGBA16I = GL_STATIC_VARIABLES.RGBA16I,
  RGB16I = GL_STATIC_VARIABLES.RGB16I,
  RGBA8I = GL_STATIC_VARIABLES.RGBA8I,
  RGB8I = GL_STATIC_VARIABLES.RGB8I,
  RED_INTEGER = GL_STATIC_VARIABLES.RED_INTEGER,
  RGB_INTEGER = GL_STATIC_VARIABLES.RGB_INTEGER,
  RGBA_INTEGER = GL_STATIC_VARIABLES.RGBA_INTEGER,
  R8 = GL_STATIC_VARIABLES.R8,
  RG8 = GL_STATIC_VARIABLES.RG8,
  R16F = GL_STATIC_VARIABLES.R16F,
  R32F = GL_STATIC_VARIABLES.R32F,
  RG16F = GL_STATIC_VARIABLES.RG16F,
  RG32F = GL_STATIC_VARIABLES.RG32F,
  R8I = GL_STATIC_VARIABLES.R8I,
  R8UI = GL_STATIC_VARIABLES.R8UI,
  R16I = GL_STATIC_VARIABLES.R16I,
  R16UI = GL_STATIC_VARIABLES.R16UI,
  R32I = GL_STATIC_VARIABLES.R32I,
  R32UI = GL_STATIC_VARIABLES.R32UI,
  RG8I = GL_STATIC_VARIABLES.RG8I,
  RG8UI = GL_STATIC_VARIABLES.RG8UI,
  RG16I = GL_STATIC_VARIABLES.RG16I,
  RG16UI = GL_STATIC_VARIABLES.RG16UI,
  RG32I = GL_STATIC_VARIABLES.RG32I,
  RG32UI = GL_STATIC_VARIABLES.RG32UI,
  R8_SNORM = GL_STATIC_VARIABLES.R8_SNORM,
  RG8_SNORM = GL_STATIC_VARIABLES.RG8_SNORM,
  RGB8_SNORM = GL_STATIC_VARIABLES.RGB8_SNORM,
  RGBA8_SNORM = GL_STATIC_VARIABLES.RGBA8_SNORM,
  RGB10_A2UI = GL_STATIC_VARIABLES.RGB10_A2UI,
  TEXTURE_IMMUTABLE_FORMAT = GL_STATIC_VARIABLES.TEXTURE_IMMUTABLE_FORMAT,
  TEXTURE_IMMUTABLE_LEVELS = GL_STATIC_VARIABLES.TEXTURE_IMMUTABLE_LEVELS,
}
