packages:
  - apps/*
  - packages/*

catalog:
  '@corvu/drawer': ^0.2.4
  '@kobalte/core': ^0.13.11
  '@mdx-js/mdx': ^3.1.1
  '@mdx-js/rollup': ^3.1.1
  '@playwright/test': ^1.60.0
  '@solid-primitives/active-element': ^2.1.5
  '@solid-primitives/context': 0.3.2
  '@solid-primitives/cursor': ^0.1.2
  '@solid-primitives/event-listener': ^2.4.5
  '@solid-primitives/memo': ^1.4.5
  '@solid-primitives/props': 3.2.3
  '@solid-primitives/scheduled': ^1.5.3
  '@solid-primitives/set': ^0.7.3
  '@solid-primitives/timer': 1.4.4
  '@solid-primitives/utils': ^6.4.0
  '@solidjs/router': 0.16.1
  '@testing-library/jest-dom': ^6.9.1
  '@unocss/reset': 66.6.8
  '@unocss/vite': 66.6.8
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  jsdom: ^29.1.1
  shiki: ^4.1.0
  solid-js: ^1.9.12
  tailwind-merge: ^3.6.0
  typegpu-runtime-inspector-mcp: ^0.3.0
  typescript: ^6.0.3
  vite: 8.0.13
  vite-plugin-solid: 2.11.12
  vite-tsconfig-paths: ^6.1.1
  vitest: 4.1.6

catalogMode: strict

peerDependencyRules:
  allowedVersions:
    grid-engine>phaser: 4.1.0
    tsconfck>typescript: 6.0.3
