import { expect, it } from 'vitest';
import { defaultBrush, type Sample } from './brush';
import reference from './fixtures/saiFilter.json';
import { createSaiFilter, createStabilizerProcessor, saiCode, stabilizerLabel } from './stabilizerStroke';
import { defaultStrokeSettings } from './strokeSettings';

const brush = (stabilizer: number) => ({
  ...defaultBrush(),
  stroke: { ...defaultStrokeSettings(), mode: 'stabilizer' as const, stabilizer, minimum: 0, maximum: 1 }
});
const pen = (x: number, y: number, time: number, pressure = 0.5): Sample => ({
  x,
  y,
  time,
  pressure,
  pointerType: 'pen'
});

it('filters exactly as SAI does, checked against its reconstruction from the machine code', () => {
  // Generated by `sai_filter.py` of paint-tool-sai-analysis, which matched SAI 2's x64 routines in 13,092 records.
  for (const { code, tablet, samples, outputs } of reference) {
    const [first, ...rest] = samples.map(([x, y, pressure], index) => ({
      x: x!,
      y: y!,
      pressure: pressure!,
      time: index
    }));
    const filter = createSaiFilter(code, first!, tablet);
    const filtered = [filter.initial, ...rest.map(filter.update)];
    filtered.forEach((sample, index) => {
      const [x, y, pressure] = outputs[index]!;
      expect(sample.x).toBeCloseTo(x!, 6);
      expect(sample.y).toBeCloseTo(y!, 6);
      expect(sample.pressure).toBeCloseTo(pressure!, 6);
    });
  }
});

it('maps levels to SAI codes and labels: 0 to 15, then S-1 to S-7', () => {
  expect([0, 15, 16, 22].map(saiCode)).toEqual([1, 16, 129, 135]);
  expect([0, 15, 16, 22].map(stabilizerLabel)).toEqual(['0', '15', 'S-1', 'S-7']);
});

it('trails a steady pen by half its window, or by 7 + K(K-1)/2 samples at S levels', () => {
  for (const [level, delay] of [
    [10, 5],
    [15, 7.5],
    [16, 8],
    [22, 35]
  ] as const) {
    const filter = createSaiFilter(saiCode(level), pen(0, 0, 0), true);
    let last = filter.initial;
    for (let index = 1; index <= 2000; index++) last = filter.update(pen(index, 0, index));
    expect(2000 - last.x).toBeCloseTo(delay, 6);
  }
});

it('eases a pen stroke in from zero pressure, and keeps a mouse at its pressure', () => {
  const stroke = (pointerType: string) => {
    const processor = createStabilizerProcessor(brush(8));
    const samples = Array.from({ length: 30 }, (_, index) => ({ ...pen(index * 4, 0, index * 4, 0.8), pointerType }));
    return processor.add(samples);
  };
  const pressures = stroke('pen').map(({ pressure }) => pressure);
  expect(pressures[0]).toBe(0);
  expect(pressures.at(-1)).toBeCloseTo(0.8, 6);
  // The window over pressure starts twice as long, so it rises slower than position moves.
  expect(pressures.findIndex((pressure) => pressure > 0.79)).toBeGreaterThan(10);
  expect(stroke('mouse')[0]!.pressure).toBeCloseTo(0.8, 6);
});

it('finishes on lift by closing in on the pen as the pressure tapers quadratically to zero', () => {
  const processor = createStabilizerProcessor(brush(15));
  const drawn = processor.add(Array.from({ length: 40 }, (_, index) => pen(index * 5, 0, index * 4, 0.6)));
  expect(drawn.at(-1)!.x).toBeLessThan(195 - 30);
  const tail = processor.finish();
  expect(tail.at(-1)).toMatchObject({ x: 195, y: 0 });
  expect(tail.at(-1)!.pressure).toBeCloseTo(0, 6);
  const pressures = tail.map(({ pressure }) => pressure);
  expect(pressures.every((pressure, index) => index === 0 || pressure <= pressures[index - 1]! + 1e-9)).toBe(true);
});

it('finishes an S level along the circle the line was turning on, toward where the pen lifted', () => {
  const processor = createStabilizerProcessor(brush(18));
  // A quarter circle of radius 200 about (0, 200).
  const arc = Array.from({ length: 60 }, (_, index) => {
    const angle = (index / 59) * (Math.PI / 2);
    return pen(200 * Math.sin(angle), 200 - 200 * Math.cos(angle), index * 4, 0.6);
  });
  processor.add(arc);
  const tail = processor.finish();
  expect(tail.length).toBeGreaterThan(3);
  expect(tail.at(-1)!.pressure).toBeCloseTo(0, 6);
  // The finish stays on one circle: no point bends back toward the inside.
  const radii = tail.map(({ x, y }) => Math.hypot(x, y - 200));
  expect(Math.max(...radii) - Math.min(...radii)).toBeLessThan(40);
});

it('splits a sparse pen step along the circle through the last samples, as SAI corrects uneven packets', () => {
  const processor = createStabilizerProcessor(brush(0));
  const onCircle = (angle: number, time: number) => pen(100 * Math.sin(angle), 100 - 100 * Math.cos(angle), time);
  // Two short steps, then one four times as long: SAI inserts points on the circle before the long one.
  const output = processor.add([onCircle(0, 0), onCircle(0.05, 4), onCircle(0.1, 8), onCircle(0.3, 12)]);
  const between = output.filter(({ x }) => x > 100 * Math.sin(0.1) + 0.5 && x < 100 * Math.sin(0.3) - 0.5);
  expect(between.length).toBeGreaterThan(3);
  for (const { x, y } of between) expect(Math.hypot(x, y - 100)).toBeCloseTo(100, 0);
});

it('joins filtered points with curves drawn a pixel at a time, through every point', () => {
  const processor = createStabilizerProcessor(brush(0));
  const corners = [pen(0, 0, 0), pen(40, 0, 10), pen(40, 40, 20), pen(80, 40, 30)];
  const output = [...processor.add(corners), ...processor.finish()];
  for (const corner of corners)
    expect(output.some(({ x, y }) => Math.hypot(x - corner.x, y - corner.y) < 1e-6)).toBe(true);
  for (let index = 1; index < output.length; index++) {
    const [a, b] = [output[index - 1]!, output[index]!];
    expect(Math.hypot(b.x - a.x, b.y - a.y)).toBeLessThanOrEqual(1.5);
  }
});

it('keeps closing in on a pen held still, then rests', () => {
  const processor = createStabilizerProcessor(brush(15));
  processor.add(Array.from({ length: 20 }, (_, index) => pen(index * 5, 0, index * 4)));
  const closing = processor.idle!(200);
  expect(closing.at(-1)!.x).toBeCloseTo(95, 3);
  expect(processor.idle!(200)).toEqual([]);
});

it('steadies a shaking hand', () => {
  const processor = createStabilizerProcessor(brush(15));
  const shaking = Array.from({ length: 300 }, (_, index) => pen(index, index % 2 ? 3 : -3, index));
  const output = processor.add(shaking);
  expect(Math.max(...output.slice(40).map(({ y }) => Math.abs(y)))).toBeLessThan(0.5);
});
