"""Copy the independently built Rust/WASM package into this workspace's parser package."""
from pathlib import Path
import shutil,json,hashlib
root=Path(__file__).resolve().parents[1]
source=root.parents[2]/'photoshop-analysis/abr-wasm'
# An explicit owned output directory; never copy research fixtures or legacy compatibility code.
for name in ['dist','pkg']:
 target=root/'wasm'/name
 target.mkdir(parents=True,exist_ok=True)
 for old in target.iterdir():
  if old.is_file() and not (source/name/old.name).is_file():old.unlink()
 for p in (source/name).iterdir():
  if p.is_file():shutil.copy2(p,target/p.name)
(root/'wasm/manifest.json').write_text(json.dumps({str(p.relative_to(root/'wasm')):hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted((root/'wasm').rglob('*')) if p.is_file() and p.name!='manifest.json'},indent=2)+'\n')

# Both independent codecs share the generated field vocabulary, never implementation code.
schema=json.loads((source/'schema.json').read_text())
(root/'src/js/schema.ts').write_text('''/** Generated by scripts/sync-wasm.py from the researched Rust field catalog. */
export interface FieldRule {key:string;name:string;types:readonly string[];units:readonly string[];classes:readonly string[]}
export const schema: Readonly<Record<string,Readonly<Record<string,FieldRule>>>> = '''+json.dumps(schema['contexts'],separators=(',',':'))+''';
export const classNames: Readonly<Record<string,string>> = '''+json.dumps(schema['classes'],separators=(',',':'))+';\n')

# Keep the differential suite runnable without a sibling research checkout.
fixtures=source.parent/'abr-rs/tests/fixtures'
target=root/'tests/fixtures/researched'
for name in ['containers','descriptors']:
 (target/name).mkdir(parents=True,exist_ok=True)
 for p in sorted((fixtures/name).iterdir()):
  if p.suffix=='.abr' or p.name.endswith('.input.bin'):shutil.copy2(p,target/name/p.name)
(target/'manifest.json').write_text(json.dumps({'source':'photoshop-analysis/abr-rs/tests/fixtures','schemaSourceSha256':schema['sourceSha256'],'files':{str(p.relative_to(target)):hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted(target.rglob('*')) if p.is_file() and p.name!='manifest.json'}},indent=2)+'\n')
