[package]
name = "wasm_bindgen_example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[build]
target = "wasm32-unknown-unknown"

[workspace]
members = [
    'libs/ogl-rs',
    'libs/wgsl_to_glsl_macro',
    'libs/wgsl_to_glsl_macro_tests',
    'libs/start_wgpu',
    'libs/webgl',
    'libs/custom-renderer',
    'libs/custom-renderer-examples',
    'libs/derive_into',
    'libs/webgl_common',
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
wasm-bindgen = "0.2.95"
wasm-bindgen-futures = "0.4.45"
web-sys = "0.3.72"
js-sys = "0.3.72"
log = "0.4"
webgl_common = { path = "libs/webgl_common" }

[dependencies]
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true, features = [
    'Document',
    'Element',
    'HtmlElement',
    'HtmlCanvasElement',
    'CssStyleDeclaration',
    'WebGlBuffer',
    'WebGlVertexArrayObject',
    'WebGl2RenderingContext',
    'WebGlProgram',
    'WebGlShader',
    'Window',
    'console',
    'PointerEvent',
    'KeyboardEvent',
    'WheelEvent',
    'AddEventListenerOptions',
] }
js-sys = { workspace = true }
wgpu = { version = "23.0.0", features = ["webgpu"] }
lyon = { version = "1.0.1", features = ["extra"] }
wgsl_to_glsl_macro = { path = "./libs/wgsl_to_glsl_macro" }
glow = { version = "0.15.0" }
bytemuck = { version = "1.19.0" }
