/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_convertoutcome_free: (a: number, b: number) => void;
export const __wbg_decodeddocument_free: (a: number, b: number) => void;
export const __wbg_decodeoutcome_free: (a: number, b: number) => void;
export const convertPdf: (a: number, b: number) => number;
export const convertoutcome_errorCode: (a: number) => [number, number];
export const convertoutcome_errorMessage: (a: number) => [number, number];
export const convertoutcome_takeBytes: (a: number) => [number, number];
export const decodeCmykJpeg: (a: number, b: number, c: number, d: number) => number;
export const decodeDocument: (a: number, b: number) => number;
export const decodeddocument_dimensions: (a: number) => [number, number];
export const decodeddocument_profile: (a: number) => number;
export const decodeddocument_takeAtlas: (a: number) => [number, number];
export const decodeddocument_takeAtlasVertices: (a: number) => [number, number];
export const decodeddocument_takeBlends: (a: number) => [number, number];
export const decodeddocument_takeClips: (a: number) => [number, number];
export const decodeddocument_takeCurveBins: (a: number) => [number, number];
export const decodeddocument_takeCurves: (a: number) => [number, number];
export const decodeddocument_takeGroups: (a: number) => [number, number];
export const decodeddocument_takeImagePixels: (a: number) => [number, number];
export const decodeddocument_takeImageTable: (a: number) => [number, number];
export const decodeddocument_takeInstances: (a: number) => [number, number];
export const decodeddocument_takeMaskTransfers: (a: number) => [number, number];
export const decodeddocument_takePages: (a: number) => [number, number];
export const decodeddocument_takePositionsX: (a: number) => [number, number];
export const decodeddocument_takePositionsY: (a: number) => [number, number];
export const decodeddocument_takeRadialGradients: (a: number) => [number, number];
export const decodeddocument_takeVertices: (a: number) => [number, number];
export const decodeoutcome_errorCode: (a: number) => [number, number];
export const decodeoutcome_errorMessage: (a: number) => [number, number];
export const decodeoutcome_takeDocument: (a: number) => number;
export const importPdf: (a: number, b: number, c: number) => number;
export const rasteroutcome_takePixels: (a: number) => [number, number];
export const rasteroutcome_errorMessage: (a: number) => [number, number];
export const rasteroutcome_errorCode: (a: number) => [number, number];
export const __wbg_rasteroutcome_free: (a: number, b: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_start: () => void;
