import { createHash } from 'node:crypto';
import { expect, test } from 'vitest';
import { transferValue } from '../../../packages/abr-brush/src/transferDynamics';
import { brushToFormValues } from '@app-game/abr-brush/form';
import { createAbrStrokeSampler, stampStride, strokeCompositeOpacity } from '@app-game/abr-brush/stroke';

test('matches 648 executions of Photoshop’s flow and opacity evaluators', () => {
  const bytes = Buffer.alloc(648 * 16);
  let offset = 0;
  for (const base of [0.5, 1])
    for (const control of [0, 1, 2])
      for (const minimum of [0, 30, 100])
        for (const jitter of [0, 25, 100])
          for (const step of [0, 3, 12])
            for (const pressure of [0, 0.2, 0.8, 1]) {
              const states = [1234567, 1234567];
              const evaluate = (maximum: number, channel: number) => transferValue(
                maximum, control, 10, minimum, jitter, pressure, step, () => {
                  states[channel] = (states[channel]! * 16807) % 2147483647;
                  return states[channel]! / 2147483648;
                }
              );
              bytes.writeFloatLE(evaluate(base, 0), offset);
              bytes.writeFloatLE(evaluate(1, 1), offset + 4);
              bytes.writeUInt32LE(states[0]!, offset + 8);
              bytes.writeUInt32LE(states[1]!, offset + 12);
              offset += 16;
            }
  // Generated by executing unchanged Photoshop 26.0 ARM64 code, not a host renderer.
  expect(createHash('sha256').update(bytes).digest('hex')).toBe('16532c7fa6ae174387eb8e490583bc3f5ee8c4ba9f378400677e2a7e8ed50323');
});

test('pressure jitter can increase a partial value and reflects above full coverage', () => {
  expect(transferValue(1, 2, 10, 0, 100, 0.25, 0, () => 0.75)).toBe(0.375);
  expect(transferValue(1, 2, 10, 0, 100, 0.8, 0, () => 0.75)).toBeCloseTo(0.8);
});

test('Paintbrush transfer streams survive preview and input batching independently', () => {
  const values = brushToFormValues({ id: 'transfer', name: 'Transfer', type: 'computed', settings: {} });
  values.useTransfer = true;
  Object.assign(values.transfer, { flowControl: 2, opacityControl: 2, flowJitter: 100, opacityJitter: 100 });
  const input = { values, size: 20, color: '#000000', flow: 0.5, opacity: 1, seed: 1234567 };
  const tip = { width: 32, height: 32 };
  const start = { x: 0, y: 0, pressure: 0.25, tiltX: 0, tiltY: 0, rotation: 0, time: 0 };
  const end = { ...start, x: 300, time: 30 };
  const whole = createAbrStrokeSampler(input, tip).add([start, end]);
  const split = createAbrStrokeSampler(input, tip);
  const first = split.add([start]);
  split.preview([end]);
  const rest = split.add([end]);
  expect(new Float32Array([...first.data, ...rest.data])).toEqual(whole.data);
  const withoutFlowJitter = createAbrStrokeSampler({
    ...input, values: { ...values, transfer: { ...values.transfer, flowJitter: 0 } }
  }, tip).add([start, end]);
  const opacity = Array.from({ length: whole.count }, (_, i) => whole.data[i * stampStride + 9]!);
  expect(opacity).toEqual(Array.from({ length: whole.count }, (_, i) => withoutFlowJitter.data[i * stampStride + 9]!));
  expect(Math.max(...opacity)).toBeGreaterThan(0.35);
  expect(Math.min(...opacity)).toBeLessThan(0.15);
});


test('Paintbrush keeps global opacity out of per-dab transfer and secondary masks', () => {
  const values = brushToFormValues({ id: 'opacity', name: 'Opacity', type: 'computed', settings: {} });
  values.useTransfer = true;
  Object.assign(values.transfer, { opacityControl: 2, opacityMinimum: 0 });
  const input = { values, size: 20, color: '#000000', flow: 1, opacity: 0.5, seed: 1234567 };
  const point = { x: 0, y: 0, pressure: 0.25, tiltX: 0, tiltY: 0, rotation: 0, time: 0 };
  const tip = { width: 32, height: 32 };
  const half = createAbrStrokeSampler(input, tip).add([point]);
  const full = createAbrStrokeSampler({ ...input, opacity: 1 }, tip).add([point]);
  expect(half.data).toEqual(full.data);
  expect(half.data[9]).toBe(0.25);
  expect(strokeCompositeOpacity(input)).toBe(128 / 255);
  expect(strokeCompositeOpacity({ ...input, stampRole: 'secondary' })).toBe(1);
  expect(strokeCompositeOpacity({ ...input, values: { ...values, tool: { ...values.tool, type: 'SmTl' } } })).toBe(1);
});
